import { test, expect } from '@playwright/test';
test('test', async function({ page })  {
  await page.goto('https://app.mytaxprepoffice.com/');
  await page.getByRole('button', { name: 'Click Here' }).click();
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByPlaceholder('Enter email address').click();
  await page.getByPlaceholder('Enter email address').fill('testauto22@yopmail.com');
  await page.getByPlaceholder('Enter email address').press('Tab');
  await page.getByPlaceholder('Enter your first name').fill('One');
  await page.getByPlaceholder('Enter your first name').press('Tab');
  await page.getByPlaceholder('Enter your last name').fill('Test');
  await page.getByPlaceholder('Enter your last name').press('Tab');
  await page.getByRole('button').first().press('Tab');
  await page.getByPlaceholder('Enter your phone no').fill('(112) 211-2222');
  await page.getByPlaceholder('Enter your phone no').press('Tab');
  await page.getByPlaceholder('Enter your firm name').fill('Auto Test One 2');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByPlaceholder('Enter password').click();
  await page.getByPlaceholder('Enter password').fill('Test@2023');
  await page.getByPlaceholder('Enter password').press('Tab');
  await page.getByPlaceholder('Enter confirm password').fill('Test@2023');
  await page.getByPlaceholder('Enter confirm password').press('Tab');
  await page.locator('#securityQuestion').press('ArrowDown');
  await page.locator('#securityQuestion').press('Tab');
  await page.getByPlaceholder('Answer').fill('me');
  await page.getByPlaceholder('Answer').press('Tab');
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByText('X', { exact: true }).click();
  await page.getByRole('button', { name: 'Yes I\'m in!' }).click();
  await page.locator('a').filter({ hasText: 'One Test' }).click();
  await page.getByRole('link', { name: 'Log Out' }).click();
});
